### PR TITLE
Update gateway tests to get them mostly passing

### PR DESCRIPTION
**Pull request by isuftin**
The gateway responses have changed so the tests are being changed to meet those responses.

I am still seeing an issue in that some of the tests will pass in the first thread, then fail in the second thread of the same jmeter test run. The failures are due to size assertions on the response data. The response data differs between thread runs.

My assumption is that subsequent threads work against an application which has already had whatever the test adds to the database, added to it so the response is going to be different. 

Currently, the gateway tests run twice (two users). It might be that this test suite should only run once or figure out a way to bring the app's data back to initial state before the second run.

```
# Perform Full Valid Add Workflow
Failing: {"name":"Validate and Process D dot File Workflow","inputFileName":"jmeter.server.1.add.1","reportDateTime":"2019-02-05T13:41:18.201Z","userName":"user","workflowSteps":[],"sites":[],"numberSiteSuccess":3,"numberSiteFailure":0}

Passing: {"name":"Validate and Process D dot File Workflow","inputFileName":"jmeter.server.1.add.2","reportDateTime":"2019-02-05T13:41:20.023Z","userName":"user","workflowSteps":[],"sites":[{"agencyCode":"USGS ","siteNumber":"1000000004     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKNRWSCHLINGERAVEWESTALLISWI': USGS-1000000001, stateFipsCode: 55\"}}"},{"name":"Process Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]},{"agencyCode":"USGS ","siteNumber":"1000000005     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKATWBLUEMOUNDRDELMGROVEWI': USGS-1000000002, stateFipsCode: 55\"}}"},{"name":"Process Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]},{"agencyCode":"USGS ","siteNumber":"1000000006     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKATUNNAMEDROADELMGROVEWI': USGS-1000000003, stateFipsCode: 55\"}}"},{"name":"Process Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]}],"numberSiteSuccess":0,"numberSiteFailure":3}

# Perform Full Add Workflow - duplicate error

Failing: {"name":"Validate and Process D dot File Workflow","inputFileName":"jmeter.server.1.add.1","reportDateTime":"2019-02-05T13:41:18.459Z","userName":"user","workflowSteps":[],"sites":[{"agencyCode":"USGS ","siteNumber":"1000000001     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKNRWSCHLINGERAVEWESTALLISWI': USGS-1000000001, stateFipsCode: 55\",\"duplicate_site\":\"Duplicate Agency Code and Site Number found in MLR.\"}}"},{"name":"Process Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]},{"agencyCode":"USGS ","siteNumber":"1000000002     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKATWBLUEMOUNDRDELMGROVEWI': USGS-1000000002, stateFipsCode: 55\",\"duplicate_site\":\"Duplicate Agency Code and Site Number found in MLR.\"}}"},{"name":"Process Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]},{"agencyCode":"USGS ","siteNumber":"1000000003     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKATUNNAMEDROADELMGROVEWI': USGS-1000000003, stateFipsCode: 55\",\"duplicate_site\":\"Duplicate Agency Code and Site Number found in MLR.\"}}"},{"name":"Process Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]}],"numberSiteSuccess":0,"numberSiteFailure":3}

Passing: {"name":"Validate and Process D dot File Workflow","inputFileName":"jmeter.server.1.add.2","reportDateTime":"2019-02-05T13:41:20.258Z","userName":"user","workflowSteps":[],"sites":[{"agencyCode":"USGS ","siteNumber":"1000000004     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKNRWSCHLINGERAVEWESTALLISWI': USGS-1000000001, stateFipsCode: 55\"}}"},{"name":"Process Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]},{"agencyCode":"USGS ","siteNumber":"1000000005     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKATWBLUEMOUNDRDELMGROVEWI': USGS-1000000002, stateFipsCode: 55\"}}"},{"name":"Process Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]},{"agencyCode":"USGS ","siteNumber":"1000000006     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKATUNNAMEDROADELMGROVEWI': USGS-1000000003, stateFipsCode: 55\"}}"},{"name":"Process Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]}],"numberSiteSuccess":0,"numberSiteFailure":3}

# Perform add validation - failure:
Failing: {"name":"Validate D dot File","inputFileName":"jmeter.server.1.add.2","reportDateTime":"2019-02-05T13:41:26.335Z","userName":"user","workflowSteps":[],"sites":[{"agencyCode":"USGS ","siteNumber":"1000000004     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKNRWSCHLINGERAVEWESTALLISWI': USGS-1000000001, stateFipsCode: 55\"}}"},{"name":"Validate Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]},{"agencyCode":"USGS ","siteNumber":"1000000005     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKATWBLUEMOUNDRDELMGROVEWI': USGS-1000000002, stateFipsCode: 55\"}}"},{"name":"Validate Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]},{"agencyCode":"USGS ","siteNumber":"1000000006     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKATUNNAMEDROADELMGROVEWI': USGS-1000000003, stateFipsCode: 55\"}}"},{"name":"Validate Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]}],"numberSiteSuccess":0,"numberSiteFailure":3}

Passing: {"name":"Validate D dot File","inputFileName":"jmeter.server.1.add.1","reportDateTime":"2019-02-05T13:41:23.906Z","userName":"user","workflowSteps":[],"sites":[{"agencyCode":"USGS ","siteNumber":"1000000001     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKNRWSCHLINGERAVEWESTALLISWI': USGS-1000000001, stateFipsCode: 55\",\"duplicate_site\":\"Duplicate Agency Code and Site Number found in MLR.\"}}"},{"name":"Validate Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]},{"agencyCode":"USGS ","siteNumber":"1000000002     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKATWBLUEMOUNDRDELMGROVEWI': USGS-1000000002, stateFipsCode: 55\",\"duplicate_site\":\"Duplicate Agency Code and Site Number found in MLR.\"}}"},{"name":"Validate Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]},{"agencyCode":"USGS ","siteNumber":"1000000003     ","transactionType":"A","success":false,"steps":[{"name":"Validate Duplicate Monitoring Location Name","httpStatus":406,"success":false,"details":"{\"error_message\":{\"stationIx\":\"Duplicate normalized station name locations found for 'UNDERWOODCREEKATUNNAMEDROADELMGROVEWI': USGS-1000000003, stateFipsCode: 55\",\"duplicate_site\":\"Duplicate Agency Code and Site Number found in MLR.\"}}"},{"name":"Validate Single D dot Transaction","httpStatus":406,"success":false,"details":"{\"error_message\":\"Transaction validation failed.\"}"}]}],"numberSiteSuccess":0,"numberSiteFailure":3}
```

### CODE REVIEW

**Comment by isuftin** [comment]
An example of the same test(s) failing...then passing...

image

**Comment by isuftin** [comment]
Also I'm noticing that the behavior of the application has changed in that previously, if you submitted an action on a site that didn't exist, you'd get a 404 code response with perhaps some body data.

Now you get a 200 response with a '404' http error code in the returned message body.

Don't you think this breaks RESTful contract?

**Comment by zmoore-usgs** [comment]
@isuftin I believe the reasoning behind that change is that in many cases the 404 isn't actually considered an error on our end of things. I.E: If you go to add a new site it checks for an existing site and if it gets a 404 that's treated as a success since the site doesn't exist, as expected. 

However I don't have a ton of context on what the reasoning for that change was so probably want to chat with @kmschoep-usgs about that.

**Comment by zmoore-usgs** [comment]
In terms of the tests having different output sizes:

I think that's probably not a valid comparison anymore because the output reports also record things like the submitted date/time now which would always vary between runs and might result in different sizes depending on the amount of variance. 

Also I believe I originally worked around the "duplicate site" issue during subsequent adds by slightly modifying the site number between each thread. It looks like the error message you're getting now is complaining about a duplicate station name, which is a new check that has been added since these tests were originally written. Thinking you might just need to modify the site name that's submitted in the same way that the site number is modified between each thread run

**Comment by kmschoep-usgs** [comment]
@isuftin , can you post an example of what you're seeing?  I've done a lot of work on the reporting output, and I'm not sure what the integration tests are looking at.

**Comment by isuftin** [comment]
@kmschoep-usgs I did post above. Are you asking for some other output?

**Comment by isuftin** [comment]
@zmoore-usgs @kmschoep-usgs 

I am also seeing that the gateway test "Perform Full Export Workflow - Success" is kicking back a 500 error over 4 of 4 tests even though the response body for each looks like:

```
{"name":"Complete Export Workflow","inputFileName":null,"reportDateTime":null,"userName":null,"workflowSteps":[{"name":"Complete Export Workflow","httpStatus":200,"success":true,"details":"Transaction File created Successfully."},{"name":"Notification","httpStatus":500,"success":false,"details":"Index: 0, Size: 0"}],"sites":[{"agencyCode":"USGS","siteNumber":"1000000001","success":true,"steps":[{"name":"Location Get by AgencyCode and SiteNumber","httpStatus":200,"success":true,"details":"Location Get Successful"},{"name":"Export Add Transaction File","httpStatus":200,"success":true,"details":"Transaction File created Successfully."}]}]}
```

**Comment by kmschoep-usgs** [comment]
> 
> 
> @zmoore-usgs @kmschoep-usgs
> 
> I am also seeing that the gateway test "Perform Full Export Workflow - Success" is kicking back a 500 error over 4 of 4 tests even though the response body for each looks like:
> 
> ```
> {"name":"Complete Export Workflow","inputFileName":null,"reportDateTime":null,"userName":null,"workflowSteps":[{"name":"Complete Export Workflow","httpStatus":200,"success":true,"details":"Transaction File created Successfully."},{"name":"Notification","httpStatus":500,"success":false,"details":"Index: 0, Size: 0"}],"sites":[{"agencyCode":"USGS","siteNumber":"1000000001","success":true,"steps":[{"name":"Location Get by AgencyCode and SiteNumber","httpStatus":200,"success":true,"details":"Location Get Successful"},{"name":"Export Add Transaction File","httpStatus":200,"success":true,"details":"Transaction File created Successfully."}]}]}
> ```

@isuftin if you look at the steps, the workflow step "Notification" failed with a 500 error.

**Comment by kmschoep-usgs** [comment]
> 
> 
> @kmschoep-usgs I did post above. Are you asking for some other output?

I'd like to see an example response of "returns 200 but there are 404 error codes in the body".  Is the 200 response for the entire response, even though a site fails?  That's OK, because users can submit several sites that may each pass or fail.  If a site it attempted to be fetched from the CRU and the site doesn't exist, the CRU returns a 404.  However, in the case of adding a site, that is a good thing--no duplicates.  If it's a modify, it's a bad thing--they want to update a non-existing site.  That is why we added the "success" attributes because depending on the context, the http response can indicate an over success or failure.

**Pull request merged**
